version: '3.8'

services:
  web:
    build: .
    ports:
      - "5004:5004"
    volumes:
      - ./data:/app/data
      - .:/app
    env_file:
      - .env
    command: flask run --host=0.0.0.0 --port=5004
